// <auto-generated/> by Diplomat

#pragma warning disable 0105
using System;
using System.Runtime.InteropServices;

using Interop.Diplomat;
#pragma warning restore 0105

namespace Interop;

#nullable enable

public partial class Example: IDisposable
{
    private unsafe Raw.Example* _inner;

    /// <summary>
    /// Creates a managed <c>Example</c> from a raw handle.
    /// </summary>
    /// <remarks>
    /// Safety: you should not build two managed objects using the same raw handle (may causes use-after-free and double-free).
    /// <br/>
    /// This constructor assumes the raw struct is allocated on Rust side.
    /// If implemented, the custom Drop implementation on Rust side WILL run on destruction.
    /// </remarks>
    public unsafe Example(Raw.Example* handle)
    {
        _inner = handle;
    }

    /// <returns>
    /// A <c>Example</c> allocated on Rust side.
    /// </returns>
    public static Example New()
    {
        unsafe
        {
            Raw.Example* retVal = Raw.Example.New();
            return new Example(retVal);
        }
    }

    public void DoSomething(byte[] bytes)
    {
        unsafe
        {
            if (_inner == null)
            {
                throw new ObjectDisposedException("Example");
            }
            nuint bytesLength = (nuint)bytes.Length;
            fixed (byte* bytesPtr = bytes)
            {
                Raw.Example.DoSomething(_inner, bytesPtr, bytesLength);
            }
        }
    }

    /// <summary>
    /// Returns the underlying raw handle.
    /// </summary>
    public unsafe Raw.Example* AsFFI()
    {
        return _inner;
    }

    /// <summary>
    /// Destroys the underlying object immediately.
    /// </summary>
    public void Dispose()
    {
        unsafe
        {
            if (_inner == null)
            {
                return;
            }

            Raw.Example.Destroy(_inner);
            _inner = null;

            GC.SuppressFinalize(this);
        }
    }

    ~Example()
    {
        Dispose();
    }
}
